"""
search_engines.py
AUTO-GENERATED ï¿½ do not edit manually.
Each function is generated by discoverer.py
"""

from urllib.parse import quote_plus


async def search_biopharmadive_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.biopharmadive.com/search/?q={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        if not await page.is_checked("input#sort"):
            el = page.locator("label[for='sort']")
            if await el.is_visible(timeout=2000):
                await el.click()
                try:
                    await page.wait_for_load_state("domcontentloaded", timeout=15000)
                except Exception:
                    pass
                await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_bioprocessonline_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.bioprocessonline.com/search?keyword={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='&sort=Date']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_cellandgene_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.cellandgene.com/search?keyword={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='&sort=Date']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_dddmag_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.drugdiscoverytrends.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("select#search-sort")
        if await el.is_visible(timeout=2000):
            await el.select_option("desc")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_statnews_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.statnews.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("label:has(input[data-field='date'][data-order='desc'])")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_endpoints_news(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://endpoints.news/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, using Strategy E
    # Append most likely param observed in the page HTML
    # Since there is no clear sort parameter, we will use the default search URL
    # and rely on the website's default sorting behavior
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_drug_dev_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://drug-dev.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append most likely param
    # Since there is no clear sort control, we will use the original URL
    # and rely on the default sorting of the website
    return page.url

async def search_drugdiscoverytrends_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.drugdiscoverytrends.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("select#search-sort")
        if await el.is_visible(timeout=2000):
            await el.select_option("desc")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_globenewswire_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.globenewswire.com/en/search/keyword/{urllib.parse.quote_plus(query)}?pageSize=10"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("#global-search-expand")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # No clear sort by date option found in the provided HTML.
    # Assuming the default sort order is by date.
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_healio_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.healio.com/search#q={urllib.parse.quote_plus(query)}&firstQueryCause=searchFromLink"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("span.CoveoSort[data-caption='Date']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_labiotech_eu(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.labiotech.eu/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, append likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_lifescienceleader_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.lifescienceleader.com/search?keyword={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='&sort=Date']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_lifescivoice_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://lifescivoice.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)

    # No sort control detected, trying to append the most likely param
    # Since there is no clear sort control, we will use the default search results page
    # and assume it is sorted by date

    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_news_mit_edu(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    to_date = datetime.date.today().isoformat()
    url = f"https://news.mit.edu/search?keyword={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("#edit-publication-date-start")
        if await el.is_visible(timeout=2000):
            await el.fill(from_date)
    except Exception:
        pass
    try:
        el = page.locator("#edit-field-publication-date-end")
        if await el.is_visible(timeout=2000):
            await el.fill(to_date)
    except Exception:
        pass
    try:
        el = page.locator("#edit-submit-site-search")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_pharmabiz_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://pharmabiz.com/KeySearches.aspx?Keyword={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append a likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_pharmamanufacturing_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.pharmamanufacturing.com/search?page=1&filters=%7B%22text%22%3A%22{urllib.parse.quote_plus(query)}%22%2C%22page%22%3A1%2C%22statusText%22%3A%5B%22Published%22%5D%2C%22impliedSchedules%22%3Atrue%7D&sort=score"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator(".vs__dropdown-toggle")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
            try:
                newest_option = page.locator("text='Newest'")
                if await newest_option.is_visible(timeout=2000):
                    await newest_option.click()
                    try:
                        await page.wait_for_load_state("domcontentloaded", timeout=15000)
                    except Exception:
                        pass
                    await asyncio.sleep(1.5)
            except Exception:
                pass
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_sanger_ac_uk(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.sanger.ac.uk/search/?q={urllib.parse.quote_plus(query)}#facet=true&facet.field=%7B!ex%3Ddt%7Dhost&facet.limit=100&facet.mincount=1&json.nl=map&wt=json&rows=10&q={urllib.parse.quote_plus(query)}&start=0&all=no"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append a likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_the_scientist_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.the-scientist.com/search?term={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a.link.text-secondary.underline[href*='&sort=newest']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_weizmann_ac_il(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.weizmann.ac.il/pages/search/web?search={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append a likely param
    # Since there's no clear sort control, we'll use the default search URL
    # and rely on the site's default sorting behavior
    await asyncio.sleep(1.5)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_pharmavoice_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.pharmavoice.com/search/?q={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        if not await page.is_checked("input#sort"):
            el = page.locator("label[for='sort']")
            if await el.is_visible(timeout=2000):
                await el.click()
                try:
                    await page.wait_for_load_state("domcontentloaded", timeout=15000)
                except Exception:
                    pass
                await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_pharmaceutical_technology_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.pharmaceutical-technology.com/s?search={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("button.search-filters-btn")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    try:
        el = page.locator("li.fancytree-node:has-text('Date')")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_stocktitan_net(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.stocktitan.net/search?query={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)

    # No sort control detected, trying to append a likely param
    # Since there's no clear sort control, we'll try appending &sort=newest
    # This is a last resort and may not work
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)

    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_tldrbio_tech(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://tldrbio.tech/posts?q={urllib.parse.quote_plus(query)}&page=0&per_page=9&_data=routes%2F__loaders%2Fposts"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append the most likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_biopharmatrend_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.biopharmatrend.com/search/?q={urllib.parse.quote_plus(query)}&section=articles"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("span.top-search-switcher")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # No sort control detected, trying to append the most likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_pharma_iq_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.pharma-iq.com/search?q={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append the most likely param
    # observed in the page HTML. However, since there is no clear sort
    # parameter in the provided HTML, we will proceed with the original URL.
    # If the website supports sorting, the parameter should be extracted
    # from the HTML and appended to the URL.
    await asyncio.sleep(1.5)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_citeline_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.citeline.com/en/site-search-listing?&SearchTerm={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("button.search__sorting-button")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
            try:
                el = page.locator("a:has-text('Newest')")
                if await el.is_visible(timeout=2000):
                    await el.click()
                    try:
                        await page.wait_for_load_state("domcontentloaded", timeout=15000)
                    except Exception:
                        pass
                    await asyncio.sleep(1.5)
            except Exception:
                pass
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_ema_europa_eu(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.ema.europa.eu/en/search?search_api_fulltext={urllib.parse.quote_plus(query)}&f%5B0%5D=ema_search_custom_entity_bundle%3A001_ema_medicines_and_related&f%5B1%5D=ema_search_categories%3A83&f%5B2%5D=ema_search_categories%3A84&f%5B3%5D=ema_search_categories%3A85&f%5B4%5D=ema_medicine_bundle%3Aema_medicine&f%5B5%5D=ema_medicine_bundle%3Aema_herbal&f%5B6%5D=ema_herbal_and_authorised_medicines%3AHerbal%20and%20authorised%20medicines"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        select = page.locator("select#edit-sort-bef-combine")
        if await select.is_visible(timeout=2000):
            await select.select_option("field_ema_computed_date_field_DESC")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_sciencedaily_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://sciencedaily.com/search/?keyword={urllib.parse.quote_plus(query)}#gsc.tab=0&gsc.q={urllib.parse.quote_plus(query)}&gsc.page=1"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, appending most likely param
    url = f"https://sciencedaily.com/search/?keyword={urllib.parse.quote_plus(query)}&sort=date#gsc.tab=0&gsc.q={urllib.parse.quote_plus(query)}&gsc.page=1"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_fiercepharma_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.fiercepharma.com/search-results?fulltext_search={urllib.parse.quote_plus(query)}&dns=fiercehealthcare_com%2Cfiercebiotech_com%2Cfiercepharma_com"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("select.filter small.input-box")
        if await el.is_visible(timeout=2000):
            await el.select_option(value="field_date_published")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_pharmashots_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://pharmashots.com/?post_types=&s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)

    # No sort control detected, trying to append the most likely param
    # Since there is no clear sort control, we will use the default search results
    # and assume they are already sorted by date

    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_koreabiomed_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.koreabiomed.com/news/articleList.html?sc_word={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='sc_order_by=E']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_grandviewresearch_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.grandviewresearch.com/Filters?search={urllib.parse.quote_plus(query)}&search_submit=+"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, append likely param
    url += "&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_drughunter_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://drughunter.com/search?q={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("button:has-text('Most Recent')")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_nature_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.nature.com/search?q={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='&sort=newest']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_pharmaceuticalcommerce_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.pharmaceuticalcommerce.com/search?searchTerm={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected
    # Strategy E: Last resort only. Try appending the most likely param observed in the page HTML.
    # Since there is no sort control, we will use the original URL
    await asyncio.sleep(1.5)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_biospectrumasia_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://biospectrumasia.com/search/{urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("button.simple-icon")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_biovoicenews_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://biovoicenews.com/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, trying to append most likely param
    # Since there is no clear sort control, we will use the current URL
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_asia_nikkei_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://asia.nikkei.com/search?query={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("label[for='sortby-newest']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_medicalxpress_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://medicalxpress.com/search/?search={urllib.parse.quote_plus(query)}&s=0"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        select = page.locator("#sort")
        if await select.is_visible(timeout=2000):
            await select.select_option("1")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_onclive_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.onclive.com/search?searchTerm={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_www_cancernetwork_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.cancernetwork.com/search?searchTerm={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No sort control detected, append likely param
    url = f"https://www.cancernetwork.com/search?searchTerm={urllib.parse.quote_plus(query)}&sort=newest"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_aacrjournals_org(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://aacrjournals.org/search-results?page=1&q={urllib.parse.quote_plus(query)}&SearchSourceType=1"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[title='Sort by: Publication Date (Newest First)']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_drugdiscoverynews_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.drugdiscoverynews.com/search?term={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        el = page.locator("a[href*='&sort=newest']")
        if await el.is_visible(timeout=2000):
            await el.click()
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_fiercebiotech_com(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://www.fiercebiotech.com/search-results?fulltext_search={urllib.parse.quote_plus(query)}&dns=fiercehealthcare_com%2Cfiercebiotech_com%2Cfiercepharma_com"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    try:
        select = page.locator("select.filter.small.input-box")
        if await select.is_visible(timeout=2000):
            await select.select_option("field_date_published")
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            await asyncio.sleep(1.5)
    except Exception:
        pass
    # polite crawl delay ï¿½ prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url

async def search_nordiclifescience_org(page, query, days=7):
    import asyncio, datetime, urllib.parse
    from_date = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
    url = f"https://nordiclifescience.org/?s={urllib.parse.quote_plus(query)}"
    await page.goto(url)
    try:
        await page.wait_for_load_state("domcontentloaded", timeout=15000)
    except Exception:
        pass
    await asyncio.sleep(2)
    # No explicit sort control detected, but the results are already sorted by date
    # No need to apply any sort strategy
    # polite crawl delay — prevents IP bans on repeated calls
    await asyncio.sleep(1.5)
    return page.url
